name: release
on: [push, workflow_call]
jobs:
  release-cloud-ui:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          clean: false

      - uses: actions/setup-node@v4
        with:
          node-version: 20.10.0

      - run: |
          echo 'PACKAGE_JSON<<EOF' >> $GITHUB_ENV
          cat ./package.json >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - uses: actions/download-artifact@v4
        with:
          name: 'cloud-ui.vusion@${{ fromJson(env.PACKAGE_JSON).version }}'

      - uses: actions/wexler@v1

      - run: node ./jimmy/app/pipelines/release-cloud-ui.js