name: release
on: [push, workflow_call]
jobs:
  release-cloud-ui:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.10.0
      - uses: actions/download-artifact@v4
        with:
          name: "cloud-ui.vusion@${{github.ref_name}}"
      - run: echo "JSON=$(curl 'http://10.219.196.129:1454/github-workflows')" >> $GITHUB_ENV
      - run: git config --global user.email "${{ fromJson(env.JSON).result.email }}"
      - run: git config --global user.name "${{ fromJson(env.JSON).result.name }}"
      - run: |
          if [[ -f jimmy/package.json ]]; then
            cd jimmy
            git fetch origin
            git reset --hard origin/master
            cd ../
          else
            git clone "${{ fromJson(env.JSON).result.jimmy }}"
          fi
      - run:  |
          if [[ -f lcap-assets/package.json ]]; then
            cd lcap-assets
            git fetch origin
            git reset --hard origin/master
            git checkout master
            git reset --hard origin/master
            cd ../
          else
            git clone "${{ fromJson(env.JSON).result.lcapAssets }}"
          fi
      - run: node ./jimmy/app/pipelines/release-cloud-ui.js