name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: self-hosted
    steps:
      - run: git clone https://Baymax:ze4vCDGm7LkvBMfn2CsV@g.hz.netease.com/lixiaoshuang/jimmy.git
      - run: cd jimmy
      - run: npm install
